==========================================
SLURM_JOB_ID = 920174
SLURM_NODELIST = gnode048
SLURM_JOB_GPUS = 0,1
==========================================
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From train_single.py:13: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead.

2023-06-15 13:31:19.024163: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2023-06-15 13:31:20.569472: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:02:00.0
2023-06-15 13:31:20.569675: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: NVIDIA GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:03:00.0
2023-06-15 13:31:20.570678: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2023-06-15 13:31:20.572415: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2023-06-15 13:31:20.573790: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2023-06-15 13:31:20.574701: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2023-06-15 13:31:20.576340: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2023-06-15 13:31:20.577737: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2023-06-15 13:31:20.581574: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-06-15 13:31:20.582222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2023-06-15 13:31:20.582493: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2023-06-15 13:31:20.607699: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400015000 Hz
2023-06-15 13:31:20.609342: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xa80390 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-06-15 13:31:20.609393: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2023-06-15 13:31:20.780915: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xae3800 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-06-15 13:31:20.780973: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 2080 Ti, Compute Capability 7.5
2023-06-15 13:31:20.780988: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): NVIDIA GeForce RTX 2080 Ti, Compute Capability 7.5
2023-06-15 13:31:20.781802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: NVIDIA GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:02:00.0
2023-06-15 13:31:20.782206: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties: 
name: NVIDIA GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:03:00.0
2023-06-15 13:31:20.782269: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2023-06-15 13:31:20.782324: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2023-06-15 13:31:20.782352: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2023-06-15 13:31:20.782377: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2023-06-15 13:31:20.782402: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2023-06-15 13:31:20.782427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2023-06-15 13:31:20.782453: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-06-15 13:31:20.783882: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0, 1
2023-06-15 13:31:20.783947: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2023-06-15 13:31:20.785524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-06-15 13:31:20.785554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 1 
2023-06-15 13:31:20.785568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N N 
2023-06-15 13:31:20.785580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 1:   N N 
2023-06-15 13:31:20.786819: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10322 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
2023-06-15 13:31:20.787962: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10322 MB memory) -> physical GPU (device: 1, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:03:00.0, compute capability: 7.5)
WARNING:tensorflow:From /home2/aditya_hari/gsoc/nabu/src/trainers/GATtrainer.py:42: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

0it [00:00, ?it/s]2023-06-15 13:31:22.103086: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
0it [00:00, ?it/s]

Train Tensor shapes (nodes, labels, node1, node2, target) : 
(35426, 16) (35426, 16) (35426, 16) (35426, 16) (35426, 127)

Eval Tensor shapes (nodes, labes, node1, node2) : 
(1399, 16) (1399, 16) (1399, 16) (1399, 16) (1399, 122)

Test Tensor shapes (nodes, labes, node1, node2) : 
(1399, 16) (1399, 16) (1399, 16) (1399, 16)
Loaded Parameters..
Latest checkpoint restored!!
Traceback (most recent call last):
  File "train_single.py", line 23, in <module>
    _train_gat_trans(args)
  File "/home2/aditya_hari/gsoc/nabu/src/trainers/GATtrainer.py", line 184, in _train_gat_trans
    batch_loss, acc, ppl = train_step(nodes, labels, node1, node2, targ)
  File "/home2/aditya_hari/gsoc/nabu/src/trainers/GATtrainer.py", line 86, in train_step
    predictions = model(nodes, labels, node1, node2, targ, None)
  File "/home2/aditya_hari/gsoc/nabu/src/models/GraphAttentionModel.py", line 201, in __call__
    decoder_inputs = tf.cast(self.tgt_emb_layer(targ), dtype=tf.float32)
  File "/home2/aditya_hari/miniconda3/envs/nabu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 894, in __call__
    self._maybe_build(inputs)
  File "/home2/aditya_hari/miniconda3/envs/nabu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2146, in _maybe_build
    self.build(input_shapes)
  File "/home2/aditya_hari/gsoc/nabu/src/layers/EmbeddingLayer.py", line 34, in build
    mean=0., stddev=self.hidden_size ** -0.5))
  File "/home2/aditya_hari/miniconda3/envs/nabu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 529, in add_weight
    aggregation=aggregation)
  File "/home2/aditya_hari/miniconda3/envs/nabu/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 693, in _add_variable_with_custom_getter
    name=name, shape=shape)
  File "/home2/aditya_hari/miniconda3/envs/nabu/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 760, in _preload_simple_restoration
    checkpoint_position=checkpoint_position, shape=shape)
  File "/home2/aditya_hari/miniconda3/envs/nabu/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 75, in __init__
    self.wrapped_value.set_shape(shape)
  File "/home2/aditya_hari/miniconda3/envs/nabu/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1074, in set_shape
    (self.shape, shape))
ValueError: Tensor's shape (16000, 16) is not compatible with supplied shape [32000, 16]
